root: true

env:
  browser: true
  es2020: true
  node: true

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:jsx-a11y/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 11

plugins:
  - 'react'
  - 'prettier'
  - '@typescript-eslint'
  - 'react-hooks'
  - 'jsx-a11y'

rules:
  prettier/prettier:
    - 'error'
    - endOfLine: 'auto'
      printWidth: 100
      trailingComma: 'es5'
      semi: false
      singleQuote: true
  semi:
    - 'error'
    - 'never'
  no-throw-literal: 'warn'
  no-useless-escape: 'off'
  no-extra-boolean-cast: 'off'
  no-undef-init: 'off'
  prefer-promise-reject-errors: 'off'
  no-debugger: 'error'
  prefer-const: 'off'
  react/prop-types: 0
  react/no-set-state: 0
  strict: 0
  function-paren-newline: 0
  guard-for-in: 0
  max-len: 0
  linebreak-style: 0
  no-nested-ternary: 0
  no-underscore-dangle: 0
  comma-dangle:
    - 'error'
    - 'only-multiline'
  no-shadow: 0
  object-curly-newline: 0
  global-require: 0
  new-cap: 0
  class-methods-use-this: 0
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 0
  react/forbid-prop-types: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/anchor-is-valid: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  import/imports-first: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
  react/no-multi-comp: 0
  consistent-return: 0
  react/jsx-no-undef:
    - 2
    - allowGlobals: true
  jsx-a11y/no-static-element-interactions: 'off'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: warn
  no-console: 0
  prefer-rest-params: warn
  react/display-name: 'off'
  jsx-a11y/no-autofocus: 'off'
  jsx-a11y/no-onchange: 'off'
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-unused-vars': 'warn'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/ban-ts-ignore': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/ban-types': 'off'
