export { LeaderBoardPage } from './LeaderBoardPage'
export { Forum } from './Forum'
export { ForumTopic } from './ForumTopic'
export { ProfilePage } from './ProfilePage'
export { ErrorPage } from './ErrorPage'
export { MainPage } from './MainPage'

export * from './LoginPage'
export * from './RegisterPage'
export * from './GamePage'
